website/routes/home.py
# Import necessary modules and libraries
from flask import Blueprint, jsonify, redirect, render_template, request, session, url_for
from website.queries.oauth_queries import OAuthQueries
from website.utils.verify_user_session import verify_user_session
from urllib.parse import urlparse, parse_qs
import json

# Create a Blueprint named 'home'
home = Blueprint('home', __name__)


# Route for the home page
@home.route('/')
def index():
    """
    Redirect users to the home page if logged in,
    otherwise redirect to the login page.
    """
    user_info = session.get('user_info', None)

    if user_info is None:
        return redirect(url_for('auth.login'))

    return redirect(url_for('home.display_home'))


@home.route('/home')
def display_home():
    """
    Render the home page with user's vinyl data if logged in,
    otherwise redirect to the login page.
    """
    user_session = verify_user_session()
    user_info = session.get('user_info')
    oauth_queries = OAuthQueries(user_session)

    # Query user vinyl data from Discogs API
    discogs_data = oauth_queries.query_random_vinyls()

    return render_template('home.html', user=user_info, discogs_data=discogs_data)


@home.route('/search', methods=["POST"])
def search():
    """
    Handle search requests from the user.

    Returns:
        JSON response containing the search results.
    """
    user_session = verify_user_session()
    oauth_queries = OAuthQueries(user_session)

    search_term = request.form.get("search_term")

    # Query search vinyls data from Discogs API
    discogs_data = oauth_queries.search(search_term)

    return discogs_data


@home.route('/remove-from-collection')
def remove_from_collection():
    """
    Remove a vinyl from the user's collection.

    Returns:
        Redirects to the previous page.
    """
    # Extract the query string from the URL
    query_string = request.query_string.decode("utf-8")

    # Parse the query string to get the collection data
    query_params = parse_qs(query_string)

    collection_data = {
        "folder_id": query_params.get("folder", [""])[0],
        "release_id": query_params.get("release", [""])[0],
        "instance_id": query_params.get("instance", [""])[0]
    }

    user_session = verify_user_session()
    user_info = session.get('user_info')
    oauth_queries = OAuthQueries(user_session)

    # Query search vinyls data from Discogs API
    response = oauth_queries.remove_collection(user_info['username'], collection_data)

    # Query user collection data from Discogs API
    discogs_data = oauth_queries.query_user_collections(user=user_info['username'])

    return redirect(request.referrer)


@home.route('/add-to-collection')
def add_to_collection():
    """
    Add a vinyl to the user's collection.

    Returns:
        Redirects to the previous page.
    """
    # Extract the query string from the URL
    query_string = request.query_string.decode("utf-8")

    # Parse the query string to get the collection data
    query_params = parse_qs(query_string)

    collection_data = {
        "folder_id": query_params.get("folder", [""])[0],
        "release_id": query_params.get("release", [""])[0]
    }

    user_session = verify_user_session()
    user_info = session.get('user_info')
    oauth_queries = OAuthQueries(user_session)

    # Query search vinyls data from Discogs API
    response = oauth_queries.add_collection(user_info['username'], collection_data)

    # Query user collection data from Discogs API
    discogs_data = oauth_queries.query_user_collections(user=user_info['username'])

    return redirect(request.referrer)

website/routes/profile.py
# Import necessary modules and libraries
from flask import Blueprint, render_template, session
from website.queries.oauth_queries import OAuthQueries
from website.utils.verify_user_session import verify_user_session

# Create a Blueprint named 'home'
profile = Blueprint('profile', __name__)


# Route for the user profile page (commented out)
@profile.route('/profile')
def index():
    """
    Render the user profile page with user's collection data if logged in,
    otherwise redirect to the login page.
    """

    user_session = verify_user_session()
    user_info = session.get('user_info')

    oauth_queries = OAuthQueries(user_session)

    # Extract the username from user_info
    username = user_info['username']

    # Query user collection data from Discogs API
    discogs_data = oauth_queries.query_user_collections(user=username)

    # Render the user profile page with user's info and collection data
    return render_template('profile.html', user=user_info, discogs_data=discogs_data)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vinyl Collection Tracker</title>
  <link rel="icon" href="{{ url_for('static', filename='vinyl.png') }}" type="image/x-icon">
  <link rel='stylesheet' href={{ url_for('static',filename='index.css') }}/>
  <script src="https://kit.fontawesome.com/e50439752f.js" crossorigin="anonymous"></script>
</head>
<body>
  
  <nav>
    {% if user %}
      <div class="nav-items">
        <ul>
          <li><a class="nav-button" href='/home'>home</a></li>
          <li><a class="nav-button" href='/profile'>profile</a></li>
          <li><a class="nav-button" href='/logout'>logout</a></li>
        </ul> 
      </div>
    {% else %}
      <div class="nav-items">
        <ul>
          <form method='POST'>
            <button type='submit' id="discog_login">Login Through Discogs</button>
          </form>
        </ul> 
      </div>
    {% endif %}
  </nav>
  <div class='content'>
    {% block content%} {% endblock %}
  </div>

  <script>
    {% if discogs_data is defined %}
      console.log({{ discogs_data | tojson }});
    {% else %}
      console.log("discogs_data is not defined");
    {% endif %}
  </script>

</body>

</html>

website/templates/home.html
{% extends "base.html" %}

{%block content%} 

  {% if user %}
  <div class="header">
    <h2>Welcome back, <span style="color: #89339c">{{ user['username'] }}</span></h2>
  </div>
  <div class="search-bar-con">
    <div class="search-container">
      <form id="searchForm" method="POST" action="{{url_for('home.search')}}" class="search-form">
        <input type="text" id="searchTerm" name="searchTerm" placeholder="Search..." class="search-input">
        <button type="submit" class="search-button">Search</button>
      </form>
    </div>
  </div>
  
    <div class="vinyls">
      {% if discogs_data %}
        {% for vinyl in discogs_data %}
          <div class='vinyl-container'>
            <h4>{{vinyl['title']}}</h4>
            {% if vinyl['thumb'] %}
              <img alt='thumb' src="{{ vinyl['thumb'] }}" />
            {% else %}
              <img alt='thumb' src="../static/no-image-found.png" />
            {% endif %}
            {% if vinyl['in_collection'] != true %}
            <a class="nav-button" href="/add-to-collection?folder=1&release={{vinyl['id']}}">Add to Collection</a>
            {% endif %}
          </div>
        {% endfor %}
      {% endif %}
    </div>

  {% else %}
    <p>You are not logged in.</p>
  {% endif %}
  <script>
    document.getElementById("searchForm").addEventListener("submit", function(event) { // add event listener to listem to the submit event
      event.preventDefault(); // prevent the page from reloaded
      
      var searchTerm = document.getElementById("searchTerm").value; // get the search term from input field
      
      // create a new XMLHttpRequest object and configure it to send a POST request to the /search route
      var xhr = new XMLHttpRequest();
      xhr.open('POST', '/search', true);
      xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
      xhr.send('search_term=' + encodeURIComponent(searchTerm)); // send request

      // handle repsonse
      xhr.onreadystatechange = function(){
        if (xhr.readyState == 4 && xhr.status == 200) { // if request is complete and status is OK
          var updated_discogs_data = JSON.parse(xhr.responseText); // xhr.responseText is simply a data string, thus need to be parsed to JSON
          updatePage(updated_discogs_data); 
        }
      };

      function updatePage(updated_discogs_data){
        var vinylsContainer = document.querySelector(".vinyls");
        vinylsContainer.innerHTML = ""; // Clear the container first
        
        updated_discogs_data.forEach(function (vinyl){
            var vinylContainer = document.createElement("div");
            vinylContainer.classList.add("vinyl-container");
            vinylContainer.innerHTML = "<h4>" + vinyl.title + "</h4>";
            if (vinyl.thumb) {
                vinylContainer.innerHTML += "<img alt='thumb' src='" + vinyl.thumb + "' />";
            } else {
                vinylContainer.innerHTML += "<img alt='thumb' src='../static/no-image-found.png' />";
            }

            if (!vinyl.in_collection) {
              vinylContainer.innerHTML += "<a class='nav-button' href='/add-to-collection?folder=1&release=" + vinyl.id + "'>Add to Collection</a>"
            }

            vinylsContainer.appendChild(vinylContainer);
        });
        
      }
    })
  </script>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{%block content%}

{% if user %}
  <div>
    <h1>You're logged in.</h1>
  </div>
{% endif %}
<div class='header'>
  <h1>You have not logged in yet!</h1>
</div>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block content %}

  {% if user %}
    <div class='header'>
      <h2>{{ user['username'] }}, explore all of your saved collections!</h2>
    </div>

    <div class="vinyls">
        <div class="folders">
          {% if discogs_data %}
            {% for folder_name, collections in discogs_data.items() %}
              <h2>{{ folder_name }}</h2>
              <div class="collection-container">
                {% for collection in collections %}
                  <div class='vinyl-container'>
                    <h3>{{ collection['basic_information']['title'] }}</h3>
                    <p>{{ collection['basic_information']['artists'][0]['name'] }}</p>
                    <img alt='thumb' src="{{ collection['basic_information']['thumb'] }}" />
                    <p>{{ collection['basic_information']['year'] }}</p>
                    <a class="nav-button" href="/remove-from-collection?folder={{collection['folder_id']}}&release={{collection['id']}}&instance={{collection['instance_id']}}">Remove From Collection</a>
                  </div>

                {% endfor %}
              </div>
            {% endfor %}
          {% else %}
            <p>You have no saved collections.</p>
          {% endif %}
        </div>
    </div>
  {% else %}
    <p>You are not logged in.</p>
  {% endif %}

{% endblock %}